services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports: ["80:80", "8080:8080"]
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks: [traefik]
    labels: ["traefik.enable=true"]




  ipssi_web:
    build:
      context: .
      dockerfile: Dockerfile.httpd
    container_name: ipssi_web
    volumes: ["./projects/ipssi:/var/www/html"]
    networks: [traefik, ipssi_net]
    labels:
      - traefik.enable=true
      - traefik.http.routers.ipssi.rule=Host(`localhost`) && PathPrefix(`/ipssi`)
      - traefik.http.routers.ipssi.entrypoints=web
      - traefik.http.services.ipssi.loadbalancer.server.port=80
      - traefik.http.middlewares.ipssi-strip.stripprefix.prefixes=/ipssi
      - traefik.http.routers.ipssi.middlewares=ipssi-strip
      - traefik.docker.network=webstack-manager_traefik

  ipssi_db:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    container_name: ipssi_db
    environment: [MYSQL_ALLOW_EMPTY_PASSWORD=1, MYSQL_DATABASE=ipssi]
    volumes: ["./data/ipssi:/var/lib/mysql"]
    networks: [ipssi_net]

networks:
  traefik:
  ipssi_net:
