FROM ubuntu:22.04

ENV MARIADB_VERSION=1:10.6.16+maria~ubu2204

RUN apt-get update && \
    apt-get install -y mariadb-server=$MARIADB_VERSION && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 3306
CMD ["mysqld_safe"]