services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports: ["80:80", "8080:8080"]
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks: [traefik]
    labels: ["traefik.enable=true"]



  hello_web:
    build:
      context: .
      dockerfile: Dockerfile.httpd
    container_name: hello_web
    volumes: ["./projects/hello:/var/www/html"]
    networks: [traefik, hello_net]
    labels:
      - traefik.enable=true
      - traefik.http.routers.hello.rule=Host(`localhost`) && PathPrefix(`/hello`)
      - traefik.http.routers.hello.entrypoints=web
      - traefik.http.services.hello.loadbalancer.server.port=80
      - traefik.http.middlewares.hello-strip.stripprefix.prefixes=/hello
      - traefik.http.routers.hello.middlewares=hello-strip
      - traefik.docker.network=webstack-manager_traefik

  hello_db:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    container_name: hello_db
    environment: [MYSQL_ALLOW_EMPTY_PASSWORD=1, MYSQL_DATABASE=hello]
    volumes: ["./data/hello:/var/lib/mysql"]
    networks: [hello_net]

networks:
  traefik:
  hello_net:
